# docker-compose.yml
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - laravel
    depends_on:
      - postgres
      - mongo
      - rabbitmq
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret
      - MONGO_DB_HOST=mongo
      - MONGO_DB_PORT=27017
      - RABBITMQ_HOST=rabbitmq

  web:
    image: nginx:alpine
    container_name: laravel_web
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - laravel

  postgres:
    image: postgres:13
    container_name: laravel_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - laravel

  mongo:
    image: mongo:latest
    container_name: laravel_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - laravel

  rabbitmq:
    image: rabbitmq:3-management
    container_name: laravel_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  pgdata:
  mongodata:
